//* Login
export const USER_LOADED = 'USER_LOADED'
export const AUTH_ERROR = 'AUTH_ERROR'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAIL = 'LOGIN_FAIL'
export const LOGOUT = 'LOGOUT'
export const DELETE_ACCOUNT = 'DELETE_ACCOUNT'
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS'
export const LIMPIAR_USER = 'LIMPIAR_USER'

export const FETCH_USUARIO_REQUEST = "FETCH_USUARIO_REQUEST";
export const FETCH_USUARIO_SUCCESS = "FETCH_USUARIO_SUCCESS";
export const FETCH_USUARIO_ERROR = "FETCH_USUARIO_ERROR";
export const FETCH_CLEAR_STATE = "FETCH_CLEAR_STATE";
export const CLEAR_STATE = "CLEAR_STATE";
export const CHECKING = "CHECKING";
export const LOGIN = "LOGIN";


export const FETCH_REGISTRO_SUCCESS = "FETCH_REGISTRO_SUCCESS";
export const FETCH_REGISTRO_ERROR = "FETCH_REGISTRO_ERROR";
export const CLEAR_REGISTRO = "CLEAR_REGISTRO";

export const FETCH_REGISTROCATEGORIAS_SUCCESS =
  "FETCH_REGISTROCATEGORIAS_SUCCESS";
export const FETCH_REGISTROCATEGORIAS_ERROR = "FETCH_REGISTROCATEGORIAS_ERROR";

export const FETCH_REGISTROPUNTOS_SUCCESS = "FETCH_REGISTROPUNTOS_SUCCESS";
export const FETCH_REGISTROPUNTOS_ERROR = "FETCH_REGISTROPUNTOS_ERROR";

export const FETCH_REGISTROPRODUCTOS_SUCCESS =
  "FETCH_REGISTROPRODUCTOS_SUCCESS";
export const FETCH_REGISTROPRODUCTOS_ERROR = "FETCH_REGISTROPRODUCTOS_ERROR";

export const UPDATE_PUNTOS = "UPDATE_PUNTOS";

export const SINGLE_PUNTOS = "SINGLE_PUNTOS";

export const OPEN_MODAL = "OPEN_MODAL";
export const CLOSE_MODAL = "CLOSE_MODAL";

export const VER_USUARIOS_SUCCESS = "VER_USUARIOS_SUCCESS";

export const VER_DISTRIBUIDORES_SUCCESS = "VER_DISTRIBUIDORES_SUCCESS";

export const VER_CATEGORIAS_SUCCESS = "VER_CATEGORIAS_SUCCESS";

export const VER_PRODUCTOS_SUCCESS = "VER_PRODUCTOS_SUCCESS";

export const VER_PRODUCTO_SUCCESS = "VER_PRODUCTO_SUCESS";

export const START_GET_PRODUCTO = "START_GET_PRODUCTO";

export const VER_PUNTOS_SUCCESS = "VER_PUNTOS_SUCCESS";

export const VER_PROFILE_SUCCESS = "VER_PROFILE_SUCCESS";

export const VER_PROFILE_ERROR = " VER_PROFILE_ERROR";

export const UPDATE_PROFILE = "UPDATE_PROFILE";

